spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/cocktail
        username: barkeep
        password: onthehouse
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            show_sql: true
            ddl-auto: update

server:
    port: 8443
    ssl.key-store: classpath:ssl/keystore.p12
    ssl.key-store-password: password
    ssl.keyStoreType: PKCS12
    ssl.keyAlias: tomcat