spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/cocktail
        username: barkeep
        password: onthehouse
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            show_sql: true
            ddl-auto: update

server:
    port: 8080

github:
  client:
    clientId: 
    clientSecret: 
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
